# Generated by Django 4.1.3 on 2022-12-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_header", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("skill_header", models.CharField(max_length=100)),
            ],
        ),
    ]
