# Generated by Django 4.1.3 on 2022-12-06 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_blog_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="date",),
        migrations.RemoveField(model_name="blog", name="image",),
    ]
