# Generated by Django 4.1.3 on 2022-12-09 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_remove_project_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="url",),
        migrations.AddField(
            model_name="project",
            name="roles",
            field=models.TextField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(max_length=10000),
        ),
    ]
