# Generated by Django 4.1.3 on 2022-12-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_remove_project_url_project_roles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="roles",
            field=models.TextField(default="", max_length=10000),
        ),
    ]
