# Generated by Django 4.1.3 on 2022-12-09 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_projsummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
