# Generated by Django 4.1.3 on 2022-12-09 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_project_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project", old_name="roles", new_name="responsibilities",
        ),
        migrations.AddField(
            model_name="project",
            name="role",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
