# Generated by Django 4.1.3 on 2022-12-09 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_rename_roles_project_responsibilities_project_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project", old_name="title", new_name="project_name",
        ),
    ]
