# Generated by Django 4.1.3 on 2022-12-09 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_rename_title_project_project_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project", old_name="date", new_name="from_date",
        ),
        migrations.AddField(
            model_name="project",
            name="to_date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
