# Generated by Django 4.1.3 on 2022-12-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_alter_project_to_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="to_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
