# Generated by Django 4.1.3 on 2022-12-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_alter_projskills_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjTools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool", models.TextField(max_length=500)),
            ],
        ),
    ]
