# Generated by Django 4.1.3 on 2022-12-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_projtools"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjTechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tech_image", models.ImageField(upload_to="portfolio/tools/")),
                ("tech_description", models.TextField(max_length=10000)),
            ],
        ),
    ]
