# Generated by Django 4.1.3 on 2022-12-15 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0016_projtechstack"),
    ]

    operations = [
        migrations.AddField(
            model_name="projtechstack",
            name="tech_summary",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
