# Generated by Django 4.1.3 on 2022-12-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0018_operatigsystems"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalSkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("personal_skills", models.TextField(max_length=100)),
            ],
        ),
    ]
