# Generated by Django 4.1.3 on 2022-12-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0019_personalskills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalskills",
            name="personal_skills",
            field=models.TextField(max_length=1000),
        ),
    ]
