# Generated by Django 4.1.3 on 2022-12-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0020_alter_personalskills_personal_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domains", models.TextField(max_length=1000)),
            ],
        ),
    ]
