# Generated by Django 4.1.3 on 2022-12-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0023_pythonexpossure_python_header"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university", models.CharField(max_length=100)),
                ("degree", models.CharField(max_length=100)),
                ("year_from", models.DateField()),
                ("year_to", models.DateField()),
            ],
        ),
    ]
