# Generated by Django 4.1.3 on 2022-12-22 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0024_education"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "email",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.EmailValidator],
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField(max_length=100)),
            ],
        ),
    ]
