# Generated by Django 4.1.3 on 2022-12-24 00:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0025_contactme"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactme",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="contactme",
            name="email",
            field=models.CharField(max_length=100),
        ),
    ]
